/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminCapacityListItemDtoPaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * EnrollmentAdminCapacityApi - axios parameter creator
 */
export const EnrollmentAdminCapacityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Searches Capacity for one school - one row per program x grade x school year.
         * @param {string} tenantId 
         * @param {string} schoolCode Required - a seat count is meaningless without a school.
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {string} [grade] Optional exact match.
         * @param {string} [search] Free-text match on program name/code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCapacity: async (tenantId: string, schoolCode: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, grade?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getCapacity', 'tenantId', tenantId)
            // verify required parameter 'schoolCode' is not null or undefined
            assertParamExists('getCapacity', 'schoolCode', schoolCode)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{schoolCode}/capacity`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{schoolCode}', encodeURIComponent(String(schoolCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (grade !== undefined) {
                localVarQueryParameter['grade'] = grade;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentAdminCapacityApi - functional programming interface
 */
export const EnrollmentAdminCapacityApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentAdminCapacityApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Searches Capacity for one school - one row per program x grade x school year.
         * @param {string} tenantId 
         * @param {string} schoolCode Required - a seat count is meaningless without a school.
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {string} [grade] Optional exact match.
         * @param {string} [search] Free-text match on program name/code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCapacity(tenantId: string, schoolCode: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, grade?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminCapacityListItemDtoPaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCapacity(tenantId, schoolCode, pageSize, pageIndex, orderBy, filter, grade, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminCapacityApi.getCapacity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentAdminCapacityApi - factory interface
 */
export const EnrollmentAdminCapacityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentAdminCapacityApiFp(configuration)
    return {
        /**
         * 
         * @summary Searches Capacity for one school - one row per program x grade x school year.
         * @param {EnrollmentAdminCapacityApiGetCapacityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCapacity(requestParameters: EnrollmentAdminCapacityApiGetCapacityRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminCapacityListItemDtoPaginatedItemsViewModel> {
            return localVarFp.getCapacity(requestParameters.tenantId, requestParameters.schoolCode, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, requestParameters.grade, requestParameters.search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCapacity operation in EnrollmentAdminCapacityApi.
 */
export interface EnrollmentAdminCapacityApiGetCapacityRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * Required - a seat count is meaningless without a school.
     */
    readonly schoolCode: string

    /**
     * 
     */
    readonly pageSize?: number

    /**
     * 
     */
    readonly pageIndex?: number

    /**
     * 
     */
    readonly orderBy?: string

    /**
     * 
     */
    readonly filter?: string

    /**
     * Optional exact match.
     */
    readonly grade?: string

    /**
     * Free-text match on program name/code.
     */
    readonly search?: string
}

/**
 * EnrollmentAdminCapacityApi - object-oriented interface
 */
export class EnrollmentAdminCapacityApi extends BaseAPI {
    /**
     * 
     * @summary Searches Capacity for one school - one row per program x grade x school year.
     * @param {EnrollmentAdminCapacityApiGetCapacityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCapacity(requestParameters: EnrollmentAdminCapacityApiGetCapacityRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminCapacityApiFp(this.configuration).getCapacity(requestParameters.tenantId, requestParameters.schoolCode, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, requestParameters.grade, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }
}

