/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseResponse } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponsesSearchResponse } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcProblemDetails } from '../models';
/**
 * EnrollmentAdminResponsesApi - axios parameter creator
 */
export const EnrollmentAdminResponsesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets an Enrollment Application Response.
         * @param {string} tenantId 
         * @param {string} responseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentApplicationResponse: async (tenantId: string, responseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentApplicationResponse', 'tenantId', tenantId)
            // verify required parameter 'responseId' is not null or undefined
            assertParamExists('getEnrollmentApplicationResponse', 'responseId', responseId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/responses/{responseId}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{responseId}', encodeURIComponent(String(responseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searches Enrollment Application Responses.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentApplicationResponses: async (tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentApplicationResponses', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/responses`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentAdminResponsesApi - functional programming interface
 */
export const EnrollmentAdminResponsesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentAdminResponsesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets an Enrollment Application Response.
         * @param {string} tenantId 
         * @param {string} responseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentApplicationResponse(tenantId: string, responseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentApplicationResponse(tenantId, responseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminResponsesApi.getEnrollmentApplicationResponse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searches Enrollment Application Responses.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentApplicationResponses(tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponsesSearchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentApplicationResponses(tenantId, pageIndex, pageSize, filter, orderBy, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminResponsesApi.getEnrollmentApplicationResponses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentAdminResponsesApi - factory interface
 */
export const EnrollmentAdminResponsesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentAdminResponsesApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets an Enrollment Application Response.
         * @param {EnrollmentAdminResponsesApiGetEnrollmentApplicationResponseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentApplicationResponse(requestParameters: EnrollmentAdminResponsesApiGetEnrollmentApplicationResponseRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseResponse> {
            return localVarFp.getEnrollmentApplicationResponse(requestParameters.tenantId, requestParameters.responseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searches Enrollment Application Responses.
         * @param {EnrollmentAdminResponsesApiGetEnrollmentApplicationResponsesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentApplicationResponses(requestParameters: EnrollmentAdminResponsesApiGetEnrollmentApplicationResponsesRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponsesSearchResponse> {
            return localVarFp.getEnrollmentApplicationResponses(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getEnrollmentApplicationResponse operation in EnrollmentAdminResponsesApi.
 */
export interface EnrollmentAdminResponsesApiGetEnrollmentApplicationResponseRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly responseId: string
}

/**
 * Request parameters for getEnrollmentApplicationResponses operation in EnrollmentAdminResponsesApi.
 */
export interface EnrollmentAdminResponsesApiGetEnrollmentApplicationResponsesRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly pageIndex?: number

    /**
     * 
     */
    readonly pageSize?: number

    /**
     * 
     */
    readonly filter?: string

    /**
     * 
     */
    readonly orderBy?: string
}

/**
 * EnrollmentAdminResponsesApi - object-oriented interface
 */
export class EnrollmentAdminResponsesApi extends BaseAPI {
    /**
     * 
     * @summary Gets an Enrollment Application Response.
     * @param {EnrollmentAdminResponsesApiGetEnrollmentApplicationResponseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentApplicationResponse(requestParameters: EnrollmentAdminResponsesApiGetEnrollmentApplicationResponseRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminResponsesApiFp(this.configuration).getEnrollmentApplicationResponse(requestParameters.tenantId, requestParameters.responseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searches Enrollment Application Responses.
     * @param {EnrollmentAdminResponsesApiGetEnrollmentApplicationResponsesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentApplicationResponses(requestParameters: EnrollmentAdminResponsesApiGetEnrollmentApplicationResponsesRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminResponsesApiFp(this.configuration).getEnrollmentApplicationResponses(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(this.axios, this.basePath));
    }
}

