/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolEnabledResponseDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolListItemResponseDtoPaginatedItemsViewModel } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolMutationResultDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolResponseDto } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * EnrollmentAdminSchoolsApi - axios parameter creator
 */
export const EnrollmentAdminSchoolsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEnrollmentSchool: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteEnrollmentSchool', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteEnrollmentSchool', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Disables an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableEnrollmentSchool: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('disableEnrollmentSchool', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('disableEnrollmentSchool', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{id}/disable`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enables an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableEnrollmentSchool: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('enableEnrollmentSchool', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('enableEnrollmentSchool', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{id}/enable`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets an Enrollment School by its record id, with the programs it runs.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentSchoolById: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentSchoolById', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getEnrollmentSchoolById', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searches Enrollment Schools.
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {string} [search] Free-text match on school name or school code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentSchools: async (tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentSchools', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Full replace, not keyed on `externalDataSourceSchoolId` - use the id in the route.  `isEnabled` is never moved by this call - use `PUT .../schools/{id}/enable` or  `.../disable` instead.
         * @summary Replaces an Enrollment School by its record id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnrollmentSchool: async (tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateEnrollmentSchool', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateEnrollmentSchool', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upsert semantics: when `externalDataSourceSchoolId` is present and matches a live school  in the tenant, that school is updated - every field, including `schoolStateShortCode`, is  overwritten. A soft-deleted match is refused (recover it first). Otherwise a new school is  always inserted, keeping the external id if one was given; a `schoolStateShortCode`  collision on insert is rejected as AlreadyExists (409) rather than overwriting the existing  school - a POST with no external id no longer overwrites by code. `isEnabled` is never  moved by this call - use `PUT .../schools/{id}/enable` or `.../disable` instead.
         * @summary Creates or updates an Enrollment School, keyed on `externalDataSourceSchoolId`.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertEnrollmentSchool: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('upsertEnrollmentSchool', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/schools`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentAdminSchoolsApi - functional programming interface
 */
export const EnrollmentAdminSchoolsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentAdminSchoolsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deletes an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEnrollmentSchool(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteEnrollmentSchool(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.deleteEnrollmentSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Disables an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disableEnrollmentSchool(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolEnabledResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disableEnrollmentSchool(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.disableEnrollmentSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Enables an Enrollment School.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async enableEnrollmentSchool(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolEnabledResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.enableEnrollmentSchool(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.enableEnrollmentSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets an Enrollment School by its record id, with the programs it runs.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentSchoolById(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentSchoolById(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.getEnrollmentSchoolById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searches Enrollment Schools.
         * @param {string} tenantId 
         * @param {number} [pageSize] 
         * @param {number} [pageIndex] 
         * @param {string} [orderBy] 
         * @param {string} [filter] 
         * @param {string} [search] Free-text match on school name or school code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentSchools(tenantId: string, pageSize?: number, pageIndex?: number, orderBy?: string, filter?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolListItemResponseDtoPaginatedItemsViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentSchools(tenantId, pageSize, pageIndex, orderBy, filter, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.getEnrollmentSchools']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Full replace, not keyed on `externalDataSourceSchoolId` - use the id in the route.  `isEnabled` is never moved by this call - use `PUT .../schools/{id}/enable` or  `.../disable` instead.
         * @summary Replaces an Enrollment School by its record id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEnrollmentSchool(tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolMutationResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEnrollmentSchool(tenantId, id, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.updateEnrollmentSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upsert semantics: when `externalDataSourceSchoolId` is present and matches a live school  in the tenant, that school is updated - every field, including `schoolStateShortCode`, is  overwritten. A soft-deleted match is refused (recover it first). Otherwise a new school is  always inserted, keeping the external id if one was given; a `schoolStateShortCode`  collision on insert is rejected as AlreadyExists (409) rather than overwriting the existing  school - a POST with no external id no longer overwrites by code. `isEnabled` is never  moved by this call - use `PUT .../schools/{id}/enable` or `.../disable` instead.
         * @summary Creates or updates an Enrollment School, keyed on `externalDataSourceSchoolId`.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertEnrollmentSchool(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolMutationResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertEnrollmentSchool(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminSchoolsApi.upsertEnrollmentSchool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentAdminSchoolsApi - factory interface
 */
export const EnrollmentAdminSchoolsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentAdminSchoolsApiFp(configuration)
    return {
        /**
         * 
         * @summary Deletes an Enrollment School.
         * @param {EnrollmentAdminSchoolsApiDeleteEnrollmentSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiDeleteEnrollmentSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Disables an Enrollment School.
         * @param {EnrollmentAdminSchoolsApiDisableEnrollmentSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiDisableEnrollmentSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolEnabledResponseDto> {
            return localVarFp.disableEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enables an Enrollment School.
         * @param {EnrollmentAdminSchoolsApiEnableEnrollmentSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiEnableEnrollmentSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolEnabledResponseDto> {
            return localVarFp.enableEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets an Enrollment School by its record id, with the programs it runs.
         * @param {EnrollmentAdminSchoolsApiGetEnrollmentSchoolByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentSchoolById(requestParameters: EnrollmentAdminSchoolsApiGetEnrollmentSchoolByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolResponseDto> {
            return localVarFp.getEnrollmentSchoolById(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searches Enrollment Schools.
         * @param {EnrollmentAdminSchoolsApiGetEnrollmentSchoolsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentSchools(requestParameters: EnrollmentAdminSchoolsApiGetEnrollmentSchoolsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolListItemResponseDtoPaginatedItemsViewModel> {
            return localVarFp.getEnrollmentSchools(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, requestParameters.search, options).then((request) => request(axios, basePath));
        },
        /**
         * Full replace, not keyed on `externalDataSourceSchoolId` - use the id in the route.  `isEnabled` is never moved by this call - use `PUT .../schools/{id}/enable` or  `.../disable` instead.
         * @summary Replaces an Enrollment School by its record id.
         * @param {EnrollmentAdminSchoolsApiUpdateEnrollmentSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiUpdateEnrollmentSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolMutationResultDto> {
            return localVarFp.updateEnrollmentSchool(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Upsert semantics: when `externalDataSourceSchoolId` is present and matches a live school  in the tenant, that school is updated - every field, including `schoolStateShortCode`, is  overwritten. A soft-deleted match is refused (recover it first). Otherwise a new school is  always inserted, keeping the external id if one was given; a `schoolStateShortCode`  collision on insert is rejected as AlreadyExists (409) rather than overwriting the existing  school - a POST with no external id no longer overwrites by code. `isEnabled` is never  moved by this call - use `PUT .../schools/{id}/enable` or `.../disable` instead.
         * @summary Creates or updates an Enrollment School, keyed on `externalDataSourceSchoolId`.
         * @param {EnrollmentAdminSchoolsApiUpsertEnrollmentSchoolRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiUpsertEnrollmentSchoolRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolMutationResultDto> {
            return localVarFp.upsertEnrollmentSchool(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteEnrollmentSchool operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiDeleteEnrollmentSchoolRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for disableEnrollmentSchool operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiDisableEnrollmentSchoolRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for enableEnrollmentSchool operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiEnableEnrollmentSchoolRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getEnrollmentSchoolById operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiGetEnrollmentSchoolByIdRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getEnrollmentSchools operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiGetEnrollmentSchoolsRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly pageSize?: number

    /**
     * 
     */
    readonly pageIndex?: number

    /**
     * 
     */
    readonly orderBy?: string

    /**
     * 
     */
    readonly filter?: string

    /**
     * Free-text match on school name or school code.
     */
    readonly search?: string
}

/**
 * Request parameters for updateEnrollmentSchool operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiUpdateEnrollmentSchoolRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto
}

/**
 * Request parameters for upsertEnrollmentSchool operation in EnrollmentAdminSchoolsApi.
 */
export interface EnrollmentAdminSchoolsApiUpsertEnrollmentSchoolRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto
}

/**
 * EnrollmentAdminSchoolsApi - object-oriented interface
 */
export class EnrollmentAdminSchoolsApi extends BaseAPI {
    /**
     * 
     * @summary Deletes an Enrollment School.
     * @param {EnrollmentAdminSchoolsApiDeleteEnrollmentSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiDeleteEnrollmentSchoolRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).deleteEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Disables an Enrollment School.
     * @param {EnrollmentAdminSchoolsApiDisableEnrollmentSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public disableEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiDisableEnrollmentSchoolRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).disableEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enables an Enrollment School.
     * @param {EnrollmentAdminSchoolsApiEnableEnrollmentSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public enableEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiEnableEnrollmentSchoolRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).enableEnrollmentSchool(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets an Enrollment School by its record id, with the programs it runs.
     * @param {EnrollmentAdminSchoolsApiGetEnrollmentSchoolByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentSchoolById(requestParameters: EnrollmentAdminSchoolsApiGetEnrollmentSchoolByIdRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).getEnrollmentSchoolById(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searches Enrollment Schools.
     * @param {EnrollmentAdminSchoolsApiGetEnrollmentSchoolsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentSchools(requestParameters: EnrollmentAdminSchoolsApiGetEnrollmentSchoolsRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).getEnrollmentSchools(requestParameters.tenantId, requestParameters.pageSize, requestParameters.pageIndex, requestParameters.orderBy, requestParameters.filter, requestParameters.search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Full replace, not keyed on `externalDataSourceSchoolId` - use the id in the route.  `isEnabled` is never moved by this call - use `PUT .../schools/{id}/enable` or  `.../disable` instead.
     * @summary Replaces an Enrollment School by its record id.
     * @param {EnrollmentAdminSchoolsApiUpdateEnrollmentSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiUpdateEnrollmentSchoolRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).updateEnrollmentSchool(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upsert semantics: when `externalDataSourceSchoolId` is present and matches a live school  in the tenant, that school is updated - every field, including `schoolStateShortCode`, is  overwritten. A soft-deleted match is refused (recover it first). Otherwise a new school is  always inserted, keeping the external id if one was given; a `schoolStateShortCode`  collision on insert is rejected as AlreadyExists (409) rather than overwriting the existing  school - a POST with no external id no longer overwrites by code. `isEnabled` is never  moved by this call - use `PUT .../schools/{id}/enable` or `.../disable` instead.
     * @summary Creates or updates an Enrollment School, keyed on `externalDataSourceSchoolId`.
     * @param {EnrollmentAdminSchoolsApiUpsertEnrollmentSchoolRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upsertEnrollmentSchool(requestParameters: EnrollmentAdminSchoolsApiUpsertEnrollmentSchoolRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminSchoolsApiFp(this.configuration).upsertEnrollmentSchool(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

