/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementMutationResultDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementResponseDto } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * EnrollmentAdminRequirementsApi - axios parameter creator
 */
export const EnrollmentAdminRequirementsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a requirement. Leave `isRequired` out to create a required one. A `url`  requirement needs `url`, an absolute http or https link.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRequirement: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createRequirement', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/requirements`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a requirement (soft delete). Programs that embed it keep their copy.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRequirement: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteRequirement', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRequirement', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/requirements/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a requirement by its record id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequirementById: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getRequirementById', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRequirementById', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/requirements/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the tenant\'s requirements, sorted by code. Unpaged. A program names the ones it asks  for by id (`requirementIds`) and embeds a copy of each, taken when the program is saved.
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequirements: async (tenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getRequirements', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/requirements`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a requirement. Every field is replaced except `isRequired`, which keeps the  stored value when left out; `isUploadEnabled` must be sent. Programs keep the copy  taken when they were last saved, so a change shows on a program only after it is re-saved.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRequirement: async (tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateRequirement', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRequirement', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/requirements/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentAdminRequirementsApi - functional programming interface
 */
export const EnrollmentAdminRequirementsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentAdminRequirementsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Creates a requirement. Leave `isRequired` out to create a required one. A `url`  requirement needs `url`, an absolute http or https link.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRequirement(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementMutationResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRequirement(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRequirementsApi.createRequirement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Removes a requirement (soft delete). Programs that embed it keep their copy.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRequirement(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRequirement(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRequirementsApi.deleteRequirement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a requirement by its record id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequirementById(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequirementById(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRequirementsApi.getRequirementById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Lists the tenant\'s requirements, sorted by code. Unpaged. A program names the ones it asks  for by id (`requirementIds`) and embeds a copy of each, taken when the program is saved.
         * @param {string} tenantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequirements(tenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequirements(tenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRequirementsApi.getRequirements']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a requirement. Every field is replaced except `isRequired`, which keeps the  stored value when left out; `isUploadEnabled` must be sent. Programs keep the copy  taken when they were last saved, so a change shows on a program only after it is re-saved.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRequirement(tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementMutationResultDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRequirement(tenantId, id, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRequirementsApi.updateRequirement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentAdminRequirementsApi - factory interface
 */
export const EnrollmentAdminRequirementsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentAdminRequirementsApiFp(configuration)
    return {
        /**
         * 
         * @summary Creates a requirement. Leave `isRequired` out to create a required one. A `url`  requirement needs `url`, an absolute http or https link.
         * @param {EnrollmentAdminRequirementsApiCreateRequirementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRequirement(requestParameters: EnrollmentAdminRequirementsApiCreateRequirementRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementMutationResultDto> {
            return localVarFp.createRequirement(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a requirement (soft delete). Programs that embed it keep their copy.
         * @param {EnrollmentAdminRequirementsApiDeleteRequirementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRequirement(requestParameters: EnrollmentAdminRequirementsApiDeleteRequirementRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteRequirement(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a requirement by its record id.
         * @param {EnrollmentAdminRequirementsApiGetRequirementByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequirementById(requestParameters: EnrollmentAdminRequirementsApiGetRequirementByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementResponseDto> {
            return localVarFp.getRequirementById(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the tenant\'s requirements, sorted by code. Unpaged. A program names the ones it asks  for by id (`requirementIds`) and embeds a copy of each, taken when the program is saved.
         * @param {EnrollmentAdminRequirementsApiGetRequirementsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequirements(requestParameters: EnrollmentAdminRequirementsApiGetRequirementsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementResponseDto>> {
            return localVarFp.getRequirements(requestParameters.tenantId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a requirement. Every field is replaced except `isRequired`, which keeps the  stored value when left out; `isUploadEnabled` must be sent. Programs keep the copy  taken when they were last saved, so a change shows on a program only after it is re-saved.
         * @param {EnrollmentAdminRequirementsApiUpdateRequirementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRequirement(requestParameters: EnrollmentAdminRequirementsApiUpdateRequirementRequest, options?: RawAxiosRequestConfig): AxiosPromise<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementMutationResultDto> {
            return localVarFp.updateRequirement(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createRequirement operation in EnrollmentAdminRequirementsApi.
 */
export interface EnrollmentAdminRequirementsApiCreateRequirementRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto
}

/**
 * Request parameters for deleteRequirement operation in EnrollmentAdminRequirementsApi.
 */
export interface EnrollmentAdminRequirementsApiDeleteRequirementRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getRequirementById operation in EnrollmentAdminRequirementsApi.
 */
export interface EnrollmentAdminRequirementsApiGetRequirementByIdRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getRequirements operation in EnrollmentAdminRequirementsApi.
 */
export interface EnrollmentAdminRequirementsApiGetRequirementsRequest {
    /**
     * 
     */
    readonly tenantId: string
}

/**
 * Request parameters for updateRequirement operation in EnrollmentAdminRequirementsApi.
 */
export interface EnrollmentAdminRequirementsApiUpdateRequirementRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto
}

/**
 * EnrollmentAdminRequirementsApi - object-oriented interface
 */
export class EnrollmentAdminRequirementsApi extends BaseAPI {
    /**
     * 
     * @summary Creates a requirement. Leave `isRequired` out to create a required one. A `url`  requirement needs `url`, an absolute http or https link.
     * @param {EnrollmentAdminRequirementsApiCreateRequirementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createRequirement(requestParameters: EnrollmentAdminRequirementsApiCreateRequirementRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRequirementsApiFp(this.configuration).createRequirement(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRequirementRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a requirement (soft delete). Programs that embed it keep their copy.
     * @param {EnrollmentAdminRequirementsApiDeleteRequirementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRequirement(requestParameters: EnrollmentAdminRequirementsApiDeleteRequirementRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRequirementsApiFp(this.configuration).deleteRequirement(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a requirement by its record id.
     * @param {EnrollmentAdminRequirementsApiGetRequirementByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRequirementById(requestParameters: EnrollmentAdminRequirementsApiGetRequirementByIdRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRequirementsApiFp(this.configuration).getRequirementById(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lists the tenant\'s requirements, sorted by code. Unpaged. A program names the ones it asks  for by id (`requirementIds`) and embeds a copy of each, taken when the program is saved.
     * @param {EnrollmentAdminRequirementsApiGetRequirementsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRequirements(requestParameters: EnrollmentAdminRequirementsApiGetRequirementsRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRequirementsApiFp(this.configuration).getRequirements(requestParameters.tenantId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a requirement. Every field is replaced except `isRequired`, which keeps the  stored value when left out; `isUploadEnabled` must be sent. Programs keep the copy  taken when they were last saved, so a change shows on a program only after it is re-saved.
     * @param {EnrollmentAdminRequirementsApiUpdateRequirementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRequirement(requestParameters: EnrollmentAdminRequirementsApiUpdateRequirementRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRequirementsApiFp(this.configuration).updateRequirement(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRequirementRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

