/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EdGraphCommonErrorsCoreProblemDetails } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto } from '../models';
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationsListResponse } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationCreatedResponse } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationUpdatedResponse } from '../models';
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationsSearchResponse } from '../models';
// @ts-ignore
import type { MicrosoftAspNetCoreMvcValidationProblemDetails } from '../models';
/**
 * EnrollmentAdminRegistrationsApi - axios parameter creator
 */
export const EnrollmentAdminRegistrationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Adds one Program-seat choice to an existing Registration - the standalone counterpart to  passing initial choices at creation time.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addEnrollmentRegistrationApplication: async (tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('addEnrollmentRegistrationApplication', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addEnrollmentRegistrationApplication', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/applications`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The `contacts` array replaces/merges into the Registration\'s existing Contacts collection,  matched by `contactId` (upsert semantics) - there is no separate scalar contactId field.  The `choices` array sets the status of the Registration\'s Applications; each Application is  independently approvable - see the `applications/{applicationId}/approve` route to approve  just one without touching the others.
         * @summary Approves a Registration - assigns the linked Student and Contacts and flips its status.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveEnrollmentRegistration: async (tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('approveEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('approveEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/approve`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Same request body shape as `PUT .../registrations/{id}/approve`. Future Phase 99:  `PUT .../registrations/{id}/contacts/{id}/match` is out of scope and not implemented here.
         * @summary Approves a single Application on a Registration, independently of its siblings.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {string} applicationId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveEnrollmentRegistrationApplication: async (tenantId: string, id: string, applicationId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('approveEnrollmentRegistrationApplication', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('approveEnrollmentRegistrationApplication', 'id', id)
            // verify required parameter 'applicationId' is not null or undefined
            assertParamExists('approveEnrollmentRegistrationApplication', 'applicationId', applicationId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/applications/{applicationId}/approve`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)))
                .replace('{applicationId}', encodeURIComponent(String(applicationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a Registration.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEnrollmentRegistration: async (tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createEnrollmentRegistration', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a Registration.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEnrollmentRegistration: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('deleteEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a Registration by its id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistration: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a Registration\'s Applications - each a zero-to-many, independently approvable  Program-seat choice.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistrationApplications: async (tenantId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentRegistrationApplications', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getEnrollmentRegistrationApplications', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/applications`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Searches Registrations - a parent\'s enrollment submission requesting a seat in a School/District  Program.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistrations: async (tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('getEnrollmentRegistrations', 'tenantId', tenantId)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            if (pageIndex !== undefined) {
                localVarQueryParameter['pageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Explicitly rejects a Registration - sets its status to Rejected. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectEnrollmentRegistration: async (tenantId: string, id: string, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('rejectEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('rejectEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/reject`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Explicitly submits a Registration - sets its status to Submitted. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitEnrollmentRegistration: async (tenantId: string, id: string, body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('submitEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submitEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}/submit`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a Registration.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnrollmentRegistration: async (tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('updateEnrollmentRegistration', 'tenantId', tenantId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateEnrollmentRegistration', 'id', id)
            const localVarPath = `/tenants/{tenantId}/enrollmentadmin/registrations/{id}`
                .replace('{tenantId}', encodeURIComponent(String(tenantId)))
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oauth2", ["https://api.edgraph.com/auth/tenant"], configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnrollmentAdminRegistrationsApi - functional programming interface
 */
export const EnrollmentAdminRegistrationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EnrollmentAdminRegistrationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Adds one Program-seat choice to an existing Registration - the standalone counterpart to  passing initial choices at creation time.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addEnrollmentRegistrationApplication(tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addEnrollmentRegistrationApplication(tenantId, id, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.addEnrollmentRegistrationApplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The `contacts` array replaces/merges into the Registration\'s existing Contacts collection,  matched by `contactId` (upsert semantics) - there is no separate scalar contactId field.  The `choices` array sets the status of the Registration\'s Applications; each Application is  independently approvable - see the `applications/{applicationId}/approve` route to approve  just one without touching the others.
         * @summary Approves a Registration - assigns the linked Student and Contacts and flips its status.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveEnrollmentRegistration(tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveEnrollmentRegistration(tenantId, id, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.approveEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Same request body shape as `PUT .../registrations/{id}/approve`. Future Phase 99:  `PUT .../registrations/{id}/contacts/{id}/match` is out of scope and not implemented here.
         * @summary Approves a single Application on a Registration, independently of its siblings.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {string} applicationId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveEnrollmentRegistrationApplication(tenantId: string, id: string, applicationId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveEnrollmentRegistrationApplication(tenantId, id, applicationId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.approveEnrollmentRegistrationApplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a Registration.
         * @param {string} tenantId 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEnrollmentRegistration(tenantId: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationCreatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createEnrollmentRegistration(tenantId, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.createEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Removes a Registration.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEnrollmentRegistration(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteEnrollmentRegistration(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.deleteEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a Registration by its id.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentRegistration(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentRegistration(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.getEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a Registration\'s Applications - each a zero-to-many, independently approvable  Program-seat choice.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentRegistrationApplications(tenantId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationsListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentRegistrationApplications(tenantId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.getEnrollmentRegistrationApplications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Searches Registrations - a parent\'s enrollment submission requesting a seat in a School/District  Program.
         * @param {string} tenantId 
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {string} [filter] 
         * @param {string} [orderBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEnrollmentRegistrations(tenantId: string, pageIndex?: number, pageSize?: number, filter?: string, orderBy?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationsSearchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEnrollmentRegistrations(tenantId, pageIndex, pageSize, filter, orderBy, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.getEnrollmentRegistrations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Explicitly rejects a Registration - sets its status to Rejected. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rejectEnrollmentRegistration(tenantId: string, id: string, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rejectEnrollmentRegistration(tenantId, id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.rejectEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Explicitly submits a Registration - sets its status to Submitted. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitEnrollmentRegistration(tenantId: string, id: string, body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitEnrollmentRegistration(tenantId, id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.submitEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates a Registration.
         * @param {string} tenantId 
         * @param {string} id 
         * @param {EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto} [edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEnrollmentRegistration(tenantId: string, id: string, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationUpdatedResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEnrollmentRegistration(tenantId, id, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EnrollmentAdminRegistrationsApi.updateEnrollmentRegistration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EnrollmentAdminRegistrationsApi - factory interface
 */
export const EnrollmentAdminRegistrationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EnrollmentAdminRegistrationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Adds one Program-seat choice to an existing Registration - the standalone counterpart to  passing initial choices at creation time.
         * @param {EnrollmentAdminRegistrationsApiAddEnrollmentRegistrationApplicationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addEnrollmentRegistrationApplication(requestParameters: EnrollmentAdminRegistrationsApiAddEnrollmentRegistrationApplicationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.addEnrollmentRegistrationApplication(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * The `contacts` array replaces/merges into the Registration\'s existing Contacts collection,  matched by `contactId` (upsert semantics) - there is no separate scalar contactId field.  The `choices` array sets the status of the Registration\'s Applications; each Application is  independently approvable - see the `applications/{applicationId}/approve` route to approve  just one without touching the others.
         * @summary Approves a Registration - assigns the linked Student and Contacts and flips its status.
         * @param {EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.approveEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Same request body shape as `PUT .../registrations/{id}/approve`. Future Phase 99:  `PUT .../registrations/{id}/contacts/{id}/match` is out of scope and not implemented here.
         * @summary Approves a single Application on a Registration, independently of its siblings.
         * @param {EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationApplicationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveEnrollmentRegistrationApplication(requestParameters: EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationApplicationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.approveEnrollmentRegistrationApplication(requestParameters.tenantId, requestParameters.id, requestParameters.applicationId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a Registration.
         * @param {EnrollmentAdminRegistrationsApiCreateEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiCreateEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationCreatedResponse> {
            return localVarFp.createEnrollmentRegistration(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a Registration.
         * @param {EnrollmentAdminRegistrationsApiDeleteEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiDeleteEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a Registration by its id.
         * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.getEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a Registration\'s Applications - each a zero-to-many, independently approvable  Program-seat choice.
         * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationApplicationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistrationApplications(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationApplicationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationsListResponse> {
            return localVarFp.getEnrollmentRegistrationApplications(requestParameters.tenantId, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Searches Registrations - a parent\'s enrollment submission requesting a seat in a School/District  Program.
         * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEnrollmentRegistrations(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationsSearchResponse> {
            return localVarFp.getEnrollmentRegistrations(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Explicitly rejects a Registration - sets its status to Rejected. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {EnrollmentAdminRegistrationsApiRejectEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rejectEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiRejectEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.rejectEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Explicitly submits a Registration - sets its status to Submitted. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
         * @param {EnrollmentAdminRegistrationsApiSubmitEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiSubmitEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> {
            return localVarFp.submitEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a Registration.
         * @param {EnrollmentAdminRegistrationsApiUpdateEnrollmentRegistrationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiUpdateEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig): AxiosPromise<EnrollmentApiEnrollmentRegistrationsV1RegistrationUpdatedResponse> {
            return localVarFp.updateEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addEnrollmentRegistrationApplication operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiAddEnrollmentRegistrationApplicationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto
}

/**
 * Request parameters for approveEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto
}

/**
 * Request parameters for approveEnrollmentRegistrationApplication operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationApplicationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly applicationId: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto
}

/**
 * Request parameters for createEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiCreateEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto
}

/**
 * Request parameters for deleteEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiDeleteEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getEnrollmentRegistrationApplications operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationApplicationsRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string
}

/**
 * Request parameters for getEnrollmentRegistrations operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationsRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly pageIndex?: number

    /**
     * 
     */
    readonly pageSize?: number

    /**
     * 
     */
    readonly filter?: string

    /**
     * 
     */
    readonly orderBy?: string
}

/**
 * Request parameters for rejectEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiRejectEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly body?: object
}

/**
 * Request parameters for submitEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiSubmitEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly body?: object
}

/**
 * Request parameters for updateEnrollmentRegistration operation in EnrollmentAdminRegistrationsApi.
 */
export interface EnrollmentAdminRegistrationsApiUpdateEnrollmentRegistrationRequest {
    /**
     * 
     */
    readonly tenantId: string

    /**
     * 
     */
    readonly id: string

    /**
     * 
     */
    readonly edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto
}

/**
 * EnrollmentAdminRegistrationsApi - object-oriented interface
 */
export class EnrollmentAdminRegistrationsApi extends BaseAPI {
    /**
     * 
     * @summary Adds one Program-seat choice to an existing Registration - the standalone counterpart to  passing initial choices at creation time.
     * @param {EnrollmentAdminRegistrationsApiAddEnrollmentRegistrationApplicationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addEnrollmentRegistrationApplication(requestParameters: EnrollmentAdminRegistrationsApiAddEnrollmentRegistrationApplicationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).addEnrollmentRegistrationApplication(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminAddRegistrationApplicationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The `contacts` array replaces/merges into the Registration\'s existing Contacts collection,  matched by `contactId` (upsert semantics) - there is no separate scalar contactId field.  The `choices` array sets the status of the Registration\'s Applications; each Application is  independently approvable - see the `applications/{applicationId}/approve` route to approve  just one without touching the others.
     * @summary Approves a Registration - assigns the linked Student and Contacts and flips its status.
     * @param {EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public approveEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).approveEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Same request body shape as `PUT .../registrations/{id}/approve`. Future Phase 99:  `PUT .../registrations/{id}/contacts/{id}/match` is out of scope and not implemented here.
     * @summary Approves a single Application on a Registration, independently of its siblings.
     * @param {EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationApplicationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public approveEnrollmentRegistrationApplication(requestParameters: EnrollmentAdminRegistrationsApiApproveEnrollmentRegistrationApplicationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).approveEnrollmentRegistrationApplication(requestParameters.tenantId, requestParameters.id, requestParameters.applicationId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a Registration.
     * @param {EnrollmentAdminRegistrationsApiCreateEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiCreateEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).createEnrollmentRegistration(requestParameters.tenantId, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateRegistrationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a Registration.
     * @param {EnrollmentAdminRegistrationsApiDeleteEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiDeleteEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).deleteEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a Registration by its id.
     * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).getEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a Registration\'s Applications - each a zero-to-many, independently approvable  Program-seat choice.
     * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationApplicationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentRegistrationApplications(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationApplicationsRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).getEnrollmentRegistrationApplications(requestParameters.tenantId, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Searches Registrations - a parent\'s enrollment submission requesting a seat in a School/District  Program.
     * @param {EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEnrollmentRegistrations(requestParameters: EnrollmentAdminRegistrationsApiGetEnrollmentRegistrationsRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).getEnrollmentRegistrations(requestParameters.tenantId, requestParameters.pageIndex, requestParameters.pageSize, requestParameters.filter, requestParameters.orderBy, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Explicitly rejects a Registration - sets its status to Rejected. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
     * @param {EnrollmentAdminRegistrationsApiRejectEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rejectEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiRejectEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).rejectEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Explicitly submits a Registration - sets its status to Submitted. Terminal, like approve: a  later Update/UpdateScreen/StartOver progress recompute does not revert it.
     * @param {EnrollmentAdminRegistrationsApiSubmitEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiSubmitEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).submitEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates a Registration.
     * @param {EnrollmentAdminRegistrationsApiUpdateEnrollmentRegistrationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateEnrollmentRegistration(requestParameters: EnrollmentAdminRegistrationsApiUpdateEnrollmentRegistrationRequest, options?: RawAxiosRequestConfig) {
        return EnrollmentAdminRegistrationsApiFp(this.configuration).updateEnrollmentRegistration(requestParameters.tenantId, requestParameters.id, requestParameters.edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateRegistrationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

