/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a contact creation.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateContactRequestDto {
    /**
     * Must match the tenant in the route.
     */
    'tenantId'?: string;
    /**
     * The contact\'s identifier in the source system (SIS). Distinct from the record id, which the  service assigns and returns in the response.
     */
    'externalDataSourceContactId'?: string | null;
    /**
     * Required. Never overridable - only email and phone are.
     */
    'firstName'?: string | null;
    /**
     * Required. Never overridable - only email and phone are.
     */
    'lastName'?: string | null;
    /**
     * The SIS-sourced email. Correcting it later is an override and goes through the  `overrides/emails` route instead - see EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.UpdateContactRequestDto.
     */
    'email'?: string | null;
    /**
     * The SIS-sourced phone, on the same terms as Email.
     */
    'phone'?: string | null;
}

