/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Creates a round. Windows are added afterwards, one at a time.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateApplicationRoundRequestDto {
    'tenantId'?: string;
    'code'?: string | null;
    'schoolYear'?: string | null;
    'label'?: string | null;
    'grades'?: Array<string> | null;
    'programTypeIds'?: Array<string> | null;
}

