/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a full school replace by id (not keyed on ExternalDataSourceSchoolId).
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateSchoolRequestDto {
    /**
     * Must match the id in the route.
     */
    'id'?: string;
    /**
     * Must match the tenant in the route.
     */
    'tenantId'?: string;
    /**
     * 
     */
    'externalDataSourceSchoolId'?: string | null;
    /**
     * Required.
     */
    'schoolStateShortCode'?: string | null;
    /**
     * Required.
     */
    'schoolName'?: string | null;
    /**
     * 
     */
    'districtStateShortCode'?: string | null;
    /**
     * 
     */
    'schoolStateLongCode'?: string | null;
    /**
     * 
     */
    'schoolLocalCode'?: string | null;
    /**
     * 
     */
    'districtLocalCode'?: string | null;
    /**
     * 
     */
    'districtStateCode'?: string | null;
    /**
     * 
     */
    'districtName'?: string | null;
    /**
     * 
     */
    'gradesServed'?: Array<string> | null;
    /**
     * 
     */
    'address'?: string | null;
    /**
     * 
     */
    'lat'?: number | null;
    /**
     * 
     */
    'lon'?: number | null;
    /**
     * 
     */
    'phone'?: string | null;
}

