/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A student linked to a contact, with the association attributes read from that student\'s own  EnrollmentStudentContact entry for this contact. `studentId` is the student record id;  `studentLocalCode` is the SIS code.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactStudentDetailDto {
    'studentId'?: string | null;
    'studentLocalCode'?: string | null;
    'studentStateCode'?: string | null;
    'studentFirstName'?: string | null;
    'studentMiddleName'?: string | null;
    'studentLastName'?: string | null;
    'priority'?: number;
    'relationship'?: string | null;
    'livesWithStudent'?: boolean;
    'hasLegalCustody'?: boolean;
    'canPickUp'?: boolean;
    'isEmergency'?: boolean;
}

