/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a district catalog entry creation. No school-identifying field - that is what  distinguishes a catalog entry from a school program; see  EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.CreateSchoolProgramRequestDto for adding it to a school.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminCreateProgramCatalogEntryRequestDto {
    'tenantId'?: string;
    'code'?: string | null;
    'name'?: string | null;
    'programType'?: string | null;
    'eligibilityCriteria'?: string | null;
    'requiredDocuments'?: Array<string> | null;
    'internalDisplayName'?: string | null;
}

