/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminGradeCapacityRequestDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-requests-enrollment-admin-grade-capacity-request-dto';

/**
 * The body of a Program update. The school never changes; the program type and the requirement  set are replaced from the ids given here (an empty list clears the requirements).
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateProgramRequestDto {
    'id'?: string;
    'tenantId'?: string;
    'programCode'?: string | null;
    'programName'?: string | null;
    'programTypeId'?: string | null;
    'eligibilityCriteria'?: string | null;
    'requirementIds'?: Array<string> | null;
    'grades'?: Array<string> | null;
    'capacityByGrade'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminGradeCapacityRequestDto> | null;
    'zone'?: string | null;
    'latitude'?: number | null;
    'longitude'?: number | null;
}

