/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A contact linked to a student, joined with that contact\'s own live name/email/phone, plus the  association attributes read from this student\'s own EnrollmentStudentContact entry for the  contact. The reverse-direction sibling of EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.ContactStudentDetailDto. `id` is the  contact record id; `externalDataSourceContactId` is its SIS id, when it has one.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminStudentContactDetailDto {
    'id'?: string | null;
    'externalDataSourceContactId'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'email'?: string | null;
    'phone'?: string | null;
    'priority'?: number;
    'relationship'?: string | null;
    'livesWithStudent'?: boolean;
    'hasLegalCustody'?: boolean;
    'canPickUp'?: boolean;
    'isEmergency'?: boolean;
}

