/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a student update. As EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.UpsertStudentRequestDto, contact association is  managed exclusively through the `/students/{id}/contacts` sub-resource, not through this call.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateStudentRequestDto {
    'id'?: string;
    'tenantId'?: string;
    'studentStateCode'?: string | null;
    'externalDataSourceStudentId'?: string | null;
    'firstName'?: string | null;
    'middleName'?: string | null;
    'lastName'?: string | null;
    'birthdate'?: string | null;
    'last4SSN'?: string | null;
    'nextAddress'?: string | null;
    'nextGradeLevel'?: string | null;
    'nextSchoolStateShortCode'?: string | null;
    'nextSchoolStateCode'?: string | null;
    'nextSchoolName'?: string | null;
    'nextSchoolAddress'?: string | null;
    'eligibilityCode'?: string | null;
    'eligibilityDescription'?: string | null;
}

