/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminAllowedPathwayIdDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-allowed-pathway-id-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminStudentContactResponseDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-student-contact-response-dto';

/**
 * One Enrollment Student, from the list and the get-by-id route alike. `registrationId` is set only on  a list row that stands for a registration not yet linked to a student (a new student): that row\'s  `id` is the registration\'s id, which the get-by-id route cannot resolve, so a client must not open a  student profile from it. Absent on every real student.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminStudentResponseDto {
    'id'?: string | null;
    'tenantId'?: string | null;
    'studentLocalCode'?: string | null;
    'studentStateCode'?: string | null;
    'externalDataSourceStudentId'?: string | null;
    'allowedPathwayIds'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminAllowedPathwayIdDto> | null;
    'firstName'?: string | null;
    'middleName'?: string | null;
    'lastName'?: string | null;
    'birthdate'?: string | null;
    'last4SSN'?: string | null;
    'nextAddress'?: string | null;
    'nextGradeLevel'?: string | null;
    'nextSchoolStateShortCode'?: string | null;
    'nextSchoolStateCode'?: string | null;
    'nextSchoolName'?: string | null;
    'nextSchoolAddress'?: string | null;
    'eligibilityCode'?: string | null;
    'eligibilityDescription'?: string | null;
    'contacts'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminStudentContactResponseDto> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean;
    'registrationId'?: string | null;
}

