/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-requirement-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolAssociationDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-school-association-dto';

export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminProgramDetailDto {
    'id'?: string | null;
    'tenantId'?: string | null;
    'code'?: string | null;
    'name'?: string | null;
    'scope'?: string | null;
    'offeredAtSchoolCount'?: number;
    'programType'?: string | null;
    'eligibilityCriteria'?: string | null;
    'internalDisplayName'?: string | null;
    'grades'?: Array<string> | null;
    'schools'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolAssociationDto> | null;
    'requirements'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminRequirementDto> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'isDeleted'?: boolean;
}

