/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesObservationsObservationUserAccessResponse } from './ed-graph-http-aggregators-tenant-api-services-observations-observation-user-access-response';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiServicesObservationsSeoaaResponse } from './ed-graph-http-aggregators-tenant-api-services-observations-seoaa-response';

/**
 * ObservationAccess is null only when Identity has no ObservationAccessScope bulk result for that user  (e.g. the user has no tenant membership matching the request\'s tenantId).
 */
export interface EdGraphHttpAggregatorsTenantApiServicesObservationsObservationUserResponse {
    'userId'?: string | null;
    'firstName'?: string | null;
    'lastName'?: string | null;
    'email'?: string | null;
    'status'?: string | null;
    'source'?: string | null;
    'instructionalInsightsRole'?: string | null;
    'seoaas'?: Array<EdGraphHttpAggregatorsTenantApiServicesObservationsSeoaaResponse> | null;
    'observationAccess'?: EdGraphHttpAggregatorsTenantApiServicesObservationsObservationUserAccessResponse;
}

