/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminSchoolListItemResponseDto {
    'id'?: string | null;
    'tenantId'?: string | null;
    'externalDataSourceSchoolId'?: string | null;
    'schoolStateShortCode'?: string | null;
    'schoolName'?: string | null;
    'districtStateShortCode'?: string | null;
    'schoolStateLongCode'?: string | null;
    'schoolLocalCode'?: string | null;
    'districtLocalCode'?: string | null;
    'districtStateCode'?: string | null;
    'districtName'?: string | null;
    'gradesServed'?: Array<string> | null;
    'address'?: string | null;
    'lat'?: number | null;
    'lon'?: number | null;
    'phone'?: string | null;
    'isEnabled'?: boolean;
    'programCount'?: number;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
}

