/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternPropertiesDto {
    'fid'?: number;
    'highSchool'?: string | null;
    'elementary'?: string | null;
    'middleSchool'?: string | null;
    'hsNum'?: number;
    'esNum'?: number;
    'msNum'?: number;
    'hsDataPage'?: string | null;
    'esDataPage'?: string | null;
    'msDataPage'?: string | null;
    'feederPattern'?: string | null;
    'color'?: string | null;
}

