/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One entry in a contact\'s override history.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminContactOverrideHistoryEntryDto {
    'eventId'?: string | null;
    /**
     * Which detail this entry is about: `email` or `phone`.
     */
    'detail'?: string | null;
    /**
     * `set` or `removed`. A removal returns the detail to its SIS value.
     */
    'action'?: string | null;
    /**
     * The value this entry superseded, if any. Superseded values are kept, never deleted.
     */
    'previousValue'?: string | null;
    'newValue'?: string | null;
    'sisValue'?: string | null;
    'overriddenBy'?: string | null;
    'overriddenAt'?: string | null;
    /**
     * The student whose screen the change was made from, when one was recorded.
     */
    'actingStudentId'?: string | null;
    'studentIds'?: Array<string> | null;
}

