/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One contact link on a student. `id` is this entry\'s own identity; EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.StudentContactResponseDto.ContactId is the  contact record it links to.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminStudentContactResponseDto {
    'id'?: string | null;
    'contactId'?: string | null;
    'priority'?: number | null;
    'fullName'?: string | null;
    'relationship'?: string | null;
    'livesWithStudent'?: boolean | null;
    'hasLegalCustody'?: boolean | null;
    'canPickUp'?: boolean | null;
    'isEmergency'?: boolean | null;
}

