/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a student-contact association update - the association attributes only, on the same  full-replacement terms as EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Requests.EnrollmentAdmin.UpdateContactStudentRequestDto.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateStudentContactRequestDto {
    'priority'?: number | null;
    'relationship'?: string | null;
    'livesWithStudent'?: boolean | null;
    'hasLegalCustody'?: boolean | null;
    'canPickUp'?: boolean | null;
    'isEmergency'?: boolean | null;
}

