/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveChoiceDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-requests-enrollment-admin-registration-approve-choice-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveContactDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-requests-enrollment-admin-registration-approve-contact-dto';

/**
 * The shared body shape for both the registration-level and application-level approve calls.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveRequestDto {
    'studentLocalCode'?: string | null;
    'registrationStatus'?: string | null;
    'contacts'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveContactDto> | null;
    'choices'?: Array<EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminRegistrationApproveChoiceDto> | null;
}

