/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternPropertiesDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-feeder-pattern-properties-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminPolygonDto } from './ed-graph-http-aggregators-tenant-api-controllers-v1-view-models-responses-enrollment-admin-polygon-dto';

export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternDto {
    'id'?: string | null;
    'tenantId'?: string | null;
    'type'?: string | null;
    'geometry'?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminPolygonDto;
    'properties'?: EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminFeederPatternPropertiesDto;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
}

