/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a contact-student association update - the association attributes only. Neither the  contact nor the student themselves are editable through this route.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpdateContactStudentRequestDto {
    'priority'?: number | null;
    'relationship'?: string | null;
    'livesWithStudent'?: boolean | null;
    'hasLegalCustody'?: boolean | null;
    'canPickUp'?: boolean | null;
    'isEmergency'?: boolean | null;
}

