/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The body of a school creation or update.
 */
export interface EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsEnrollmentAdminUpsertSchoolRequestDto {
    /**
     * Must match the tenant in the route.
     */
    'tenantId'?: string;
    /**
     * When present, the upsert is keyed on this id rather than SchoolStateShortCode:  a live school with a matching external id is updated; a soft-deleted one is refused (recover it  first). When absent, a new school is always inserted, and a SchoolStateShortCode  collision on insert is rejected as AlreadyExists.
     */
    'externalDataSourceSchoolId'?: string | null;
    /**
     * Required. Unique per tenant.
     */
    'schoolStateShortCode'?: string | null;
    /**
     * Required.
     */
    'schoolName'?: string | null;
    /**
     * 
     */
    'districtStateShortCode'?: string | null;
    /**
     * 
     */
    'schoolStateLongCode'?: string | null;
    /**
     * 
     */
    'schoolLocalCode'?: string | null;
    /**
     * 
     */
    'districtLocalCode'?: string | null;
    /**
     * 
     */
    'districtStateCode'?: string | null;
    /**
     * 
     */
    'districtName'?: string | null;
    /**
     * 
     */
    'gradesServed'?: Array<string> | null;
    /**
     * 
     */
    'address'?: string | null;
    /**
     * 
     */
    'lat'?: number | null;
    /**
     * 
     */
    'lon'?: number | null;
    /**
     * 
     */
    'phone'?: string | null;
}

