/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentApplicationResponsesV1ApplicationPathwayMessage } from './enrollment-api-enrollment-application-responses-v1-application-pathway-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseContactMessage } from './enrollment-api-enrollment-application-responses-v1-application-response-contact-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseScreenMessage } from './enrollment-api-enrollment-application-responses-v1-application-response-screen-message';

export interface EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseResponse {
    'id'?: string | null;
    'tenantId'?: string | null;
    'applicationPathway'?: EnrollmentApiEnrollmentApplicationResponsesV1ApplicationPathwayMessage;
    'currentScreenCode'?: string | null;
    /**
     * Decimal progress (0-100, 2dp) carried as an invariant-culture string,  mirroring the legacy enrollmentresults.proto completedProgress convention.
     */
    'progress'?: string | null;
    'studentId'?: string | null;
    'languageCode'?: string | null;
    'contacts'?: Array<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseContactMessage> | null;
    'screens'?: Array<EnrollmentApiEnrollmentApplicationResponsesV1ApplicationResponseScreenMessage> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
    'status'?: string | null;
    'studentFirstName'?: string | null;
    'studentLastName'?: string | null;
    'studentLocalId'?: string | null;
    'nextSchoolCode'?: string | null;
    'nextSchoolName'?: string | null;
}

