/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse } from './enrollment-api-enrollment-registrations-v1-registration-response';

export interface EnrollmentApiEnrollmentRegistrationsV1RegistrationsSearchResponse {
    'pageSize'?: number;
    'pageIndex'?: number;
    'count'?: number;
    'data'?: Array<EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse> | null;
}

