/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One Program-seat choice on a Registration - zero-to-many, independently approvable. See  ApproveRegistrationApplication / GetRegistrationApplications.
 */
export interface EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationMessage {
    'applicationId'?: string | null;
    'applicationStatus'?: string | null;
    /**
     * enrollment-svc-programs._id - one school\'s offering of a program.
     */
    'programId'?: string | null;
    /**
     * The family\'s preference order within the round. 1-based and contiguous across the  registration - the matcher\'s contract. Assigned server-side, never supplied by a caller.
     */
    'rank'?: number;
    /**
     * The priority tier - sibling, staff, feeder, PreK. Unset until the priority engine stamps it.
     */
    'priority'?: number | null;
    /**
     * Foreign key into the application round this entry was submitted to.
     */
    'applicationRoundId'?: string | null;
}

