/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1PathwayMessage } from './enrollment-api-enrollment-registrations-v1-pathway-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationMessage } from './enrollment-api-enrollment-registrations-v1-registration-application-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage } from './enrollment-api-enrollment-registrations-v1-registration-contact-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationScreenMessage } from './enrollment-api-enrollment-registrations-v1-registration-screen-message';
// May contain unused imports in some cases
// @ts-ignore
import type { EnrollmentApiEnrollmentRegistrationsV1RegistrationStudentMessage } from './enrollment-api-enrollment-registrations-v1-registration-student-message';

export interface EnrollmentApiEnrollmentRegistrationsV1RegistrationResponse {
    'id'?: string | null;
    'tenantId'?: string | null;
    'pathway'?: EnrollmentApiEnrollmentRegistrationsV1PathwayMessage;
    'currentScreenCode'?: string | null;
    /**
     * Decimal progress (0-100, 2dp) carried as an invariant-culture string,  mirroring the legacy enrollmentresults.proto completedProgress convention.
     */
    'progress'?: string | null;
    'languageCode'?: string | null;
    'contacts'?: Array<EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage> | null;
    'screens'?: Array<EnrollmentApiEnrollmentRegistrationsV1RegistrationScreenMessage> | null;
    'createdBy'?: string | null;
    'createdDateTime'?: string | null;
    'lastModifiedBy'?: string | null;
    'lastModifiedDateTime'?: string | null;
    'deletedBy'?: string | null;
    'deletedDateTime'?: string | null;
    'isDeleted'?: boolean | null;
    'status'?: string | null;
    'nextSchoolStateShortCode'?: string | null;
    'nextSchoolName'?: string | null;
    'student'?: EnrollmentApiEnrollmentRegistrationsV1RegistrationStudentMessage;
    'applications'?: Array<EnrollmentApiEnrollmentRegistrationsV1RegistrationApplicationMessage> | null;
}

