/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One contact on a registration. id is the entry\'s own identity (minted once, never overwritten);  contactId is the EnrollmentContact record id the entry resolved to (the key every join goes  through; unset until resolved); externalDataSourceContactId is the SIS-side code, when known.
 */
export interface EnrollmentApiEnrollmentRegistrationsV1RegistrationContactMessage {
    'id'?: string | null;
    'contactId'?: string | null;
    'contactName'?: string | null;
    'contactPhone'?: string | null;
    'contactEmail'?: string | null;
    'externalDataSourceContactId'?: string | null;
}

