/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The student a registration is for. studentId is the EnrollmentStudent record id, all zeros until  the registration is linked; the local/state/external ids and names are denormalized from the  student or supplied by the registration flow. No id of its own.
 */
export interface EnrollmentApiEnrollmentRegistrationsV1RegistrationStudentMessage {
    'studentId'?: string | null;
    'studentLocalCode'?: string | null;
    'studentStateCode'?: string | null;
    'studentFirstName'?: string | null;
    'studentLastName'?: string | null;
    'externalDataSourceStudentId'?: string | null;
}

