/* tslint:disable */
/* eslint-disable */
/**
 * All Api
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const TenantApiPartnershipV1PartnershipScope = {
    RelatedTenantsOnly: 'RelatedTenantsOnly',
    AllActiveTenants: 'AllActiveTenants',
} as const;

export type TenantApiPartnershipV1PartnershipScope = typeof TenantApiPartnershipV1PartnershipScope[keyof typeof TenantApiPartnershipV1PartnershipScope];



